=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::InstancesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InstancesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::InstancesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstancesApi' do
    it 'should create an instact of InstancesApi' do
      @instance.should be_a(SwaggerClient::InstancesApi)
    end
  end

  # unit tests for instance_managers_get
  # Returns a list of instance managers.
  # Returns a list of instance managers.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [Array<InstanceManager>]
  describe 'instance_managers_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for instance_managers_uuid_get
  # Returns details for the specified instance manager.
  # Returns details for the specified instance manager.
  # @param uuid UUID of the instance manager to retrieve details for.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [InstanceManager]
  describe 'instance_managers_uuid_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for instance_managers_uuid_instances_get
  # Returns a list of instances managed by the specified instance manager.
  # Returns a list of instances managed by the specified instance manager.
  # @param uuid UUID of the instance manager whose instances should be retrieved.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [Array<Instances>]
  describe 'instance_managers_uuid_instances_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for instances_uuid_snapshot_post
  # Creates a snapshot of a capsule.
  # 
  # @param uuid UUID of the job from which to create the capsule.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [nil]
  describe 'instances_uuid_snapshot_post test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for tags_get
  # Lists all tags on all instance managers in the cluster. 
  # Lists all tags on all instance managers in the cluster. Requires `read` privileges on the `cluster` realm.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization 
  # @return [nil]
  describe 'tags_get test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
