=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class AuditLogItem
    # Event type.
    attr_accessor :event_type

    # Integer used as the index of an enumeration of human-readable event types (see `event_type`).
    attr_accessor :event_type_int

    # Fully-qualified name of the resource on which the auditable action was attempted.
    attr_accessor :fqn

    # Local name of the resource on which the auditable action was attempted.
    attr_accessor :localname

    # Namespace of the resource on which the auditable action was attempted.
    attr_accessor :namespace

    # Username on whose behalf the auditable action was attempted by `principal_name`.
    attr_accessor :on_behalf_of

    # Simple structured auditing data like JSON output.
    attr_accessor :payload

    # The actor (API Server or Health Manager, for example) or user that attempted the auditable action.
    attr_accessor :principal_name

    # The resource type on which the auditable action was attempted.
    attr_accessor :resource_type

    # UNIX timestamp that indicates when the event occurred.
    attr_accessor :timestamp

    # Unique identifier for the audit log entry.
    attr_accessor :uuid

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'event_type' => :'event_type',
        
        :'event_type_int' => :'event_type_int',
        
        :'fqn' => :'fqn',
        
        :'localname' => :'localname',
        
        :'namespace' => :'namespace',
        
        :'on_behalf_of' => :'on_behalf_of',
        
        :'payload' => :'payload',
        
        :'principal_name' => :'principal_name',
        
        :'resource_type' => :'resource_type',
        
        :'timestamp' => :'timestamp',
        
        :'uuid' => :'uuid'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'event_type' => :'String',
        :'event_type_int' => :'Integer',
        :'fqn' => :'String',
        :'localname' => :'String',
        :'namespace' => :'String',
        :'on_behalf_of' => :'String',
        :'payload' => :'String',
        :'principal_name' => :'String',
        :'resource_type' => :'String',
        :'timestamp' => :'Float',
        :'uuid' => :'String'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'event_type']
        self.event_type = attributes[:'event_type']
      end
      
      if attributes[:'event_type_int']
        self.event_type_int = attributes[:'event_type_int']
      end
      
      if attributes[:'fqn']
        self.fqn = attributes[:'fqn']
      end
      
      if attributes[:'localname']
        self.localname = attributes[:'localname']
      end
      
      if attributes[:'namespace']
        self.namespace = attributes[:'namespace']
      end
      
      if attributes[:'on_behalf_of']
        self.on_behalf_of = attributes[:'on_behalf_of']
      end
      
      if attributes[:'payload']
        self.payload = attributes[:'payload']
      end
      
      if attributes[:'principal_name']
        self.principal_name = attributes[:'principal_name']
      end
      
      if attributes[:'resource_type']
        self.resource_type = attributes[:'resource_type']
      end
      
      if attributes[:'timestamp']
        self.timestamp = attributes[:'timestamp']
      end
      
      if attributes[:'uuid']
        self.uuid = attributes[:'uuid']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event_type == o.event_type &&
          event_type_int == o.event_type_int &&
          fqn == o.fqn &&
          localname == o.localname &&
          namespace == o.namespace &&
          on_behalf_of == o.on_behalf_of &&
          payload == o.payload &&
          principal_name == o.principal_name &&
          resource_type == o.resource_type &&
          timestamp == o.timestamp &&
          uuid == o.uuid
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [event_type, event_type_int, fqn, localname, namespace, on_behalf_of, payload, principal_name, resource_type, timestamp, uuid].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
