=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class Instances
    # Indicates whether the routes for this instance have been announced.
    attr_accessor :announced_routes

    # UNIX timestamp for when instance was created.
    attr_accessor :created_time

    # Exit code of the main processes; should only be checked if `exited` is `true`.
    attr_accessor :exit_code

    # Set to true if the instance started and its main process managed to exit.
    attr_accessor :exited

    # Set to `true` if the instance has failed in some way.
    attr_accessor :failed

    # Name of the host the instance is running on.
    attr_accessor :host

    # UUID of the instance manager running the instance.
    attr_accessor :instance_manager

    # The sequence number of the job the instance is running.
    attr_accessor :job_version_id

    # State of the instance.
    attr_accessor :state

    # The instance's unique identifier.
    attr_accessor :uuid

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'announced_routes' => :'announced_routes',
        
        :'created_time' => :'created_time',
        
        :'exit_code' => :'exit_code',
        
        :'exited' => :'exited',
        
        :'failed' => :'failed',
        
        :'host' => :'host',
        
        :'instance_manager' => :'instance_manager',
        
        :'job_version_id' => :'job_version_id',
        
        :'state' => :'state',
        
        :'uuid' => :'uuid'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'announced_routes' => :'BOOLEAN',
        :'created_time' => :'Float',
        :'exit_code' => :'Integer',
        :'exited' => :'BOOLEAN',
        :'failed' => :'BOOLEAN',
        :'host' => :'String',
        :'instance_manager' => :'String',
        :'job_version_id' => :'Integer',
        :'state' => :'InstanceState',
        :'uuid' => :'String'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'announced_routes']
        self.announced_routes = attributes[:'announced_routes']
      end
      
      if attributes[:'created_time']
        self.created_time = attributes[:'created_time']
      end
      
      if attributes[:'exit_code']
        self.exit_code = attributes[:'exit_code']
      end
      
      if attributes[:'exited']
        self.exited = attributes[:'exited']
      end
      
      if attributes[:'failed']
        self.failed = attributes[:'failed']
      end
      
      if attributes[:'host']
        self.host = attributes[:'host']
      end
      
      if attributes[:'instance_manager']
        self.instance_manager = attributes[:'instance_manager']
      end
      
      if attributes[:'job_version_id']
        self.job_version_id = attributes[:'job_version_id']
      end
      
      if attributes[:'state']
        self.state = attributes[:'state']
      end
      
      if attributes[:'uuid']
        self.uuid = attributes[:'uuid']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          announced_routes == o.announced_routes &&
          created_time == o.created_time &&
          exit_code == o.exit_code &&
          exited == o.exited &&
          failed == o.failed &&
          host == o.host &&
          instance_manager == o.instance_manager &&
          job_version_id == o.job_version_id &&
          state == o.state &&
          uuid == o.uuid
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [announced_routes, created_time, exit_code, exited, failed, host, instance_manager, job_version_id, state, uuid].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
