=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class Package
    # The date and time when the package was created.
    attr_accessor :created_at

    # Principal name of the user who created the package.
    attr_accessor :created_by

    # List of dependencies that the package has in order to be used. A dependency expresses a requirement that a package has on an other package.
    attr_accessor :dependencies

    # List of environment variables that are added to any process that uses the package.
    attr_accessor :environment

    # Error encountered during an asynchronous operation on the package. An example is a failure encountered during instance snapshot; the ErrorMessage field on the created snapshot package would contain more information.
    attr_accessor :error_message

    # Package's fully-qualified name.
    attr_accessor :fqn

    # Package name.
    attr_accessor :name

    # List of 'provides' that the package provides for other packages to use. A 'provide' expresses a named resource that other packages or jobs can add as a dependency.
    attr_accessor :provides

    # Deprecated. Use `resources`. An object that describes the package's associated binary resource. 
    attr_accessor :resource

    # An list of objects that describes the package's associated binary resources.
    attr_accessor :resources

    # The UUID of the staging pipeline used to stage this package into a runnable state.
    attr_accessor :staging_pipeline

    # The fully-qualified name of the staging pipeline used to stage the package.
    attr_accessor :staging_pipeline_fqn

    # Package state. Possible values are `uploading`, 'staging`, `failed`, `ready`, `deleted`, and `unknown`.
    attr_accessor :state

    # Map of tags by tag name.
    attr_accessor :tags

    # The date and time when the package was most recently updated.
    attr_accessor :updated_at

    # Principal name of the last user to update the package.
    attr_accessor :updated_by

    # The package's unique identifier.
    attr_accessor :uuid

    # Package's auto-incremented version number.
    attr_accessor :version_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'created_at' => :'created_at',
        
        :'created_by' => :'created_by',
        
        :'dependencies' => :'dependencies',
        
        :'environment' => :'environment',
        
        :'error_message' => :'error_message',
        
        :'fqn' => :'fqn',
        
        :'name' => :'name',
        
        :'provides' => :'provides',
        
        :'resource' => :'resource',
        
        :'resources' => :'resources',
        
        :'staging_pipeline' => :'staging_pipeline',
        
        :'staging_pipeline_fqn' => :'staging_pipeline_fqn',
        
        :'state' => :'state',
        
        :'tags' => :'tags',
        
        :'updated_at' => :'updated_at',
        
        :'updated_by' => :'updated_by',
        
        :'uuid' => :'uuid',
        
        :'version_id' => :'version_id'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'created_at' => :'DateTime',
        :'created_by' => :'String',
        :'dependencies' => :'Array<Dependency>',
        :'environment' => :'Hash<String, String>',
        :'error_message' => :'String',
        :'fqn' => :'String',
        :'name' => :'String',
        :'provides' => :'Array<Provide>',
        :'resource' => :'PackageResource',
        :'resources' => :'Array<PackageResource>',
        :'staging_pipeline' => :'String',
        :'staging_pipeline_fqn' => :'String',
        :'state' => :'String',
        :'tags' => :'Hash<String, String>',
        :'updated_at' => :'DateTime',
        :'updated_by' => :'String',
        :'uuid' => :'String',
        :'version_id' => :'Integer'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'created_at']
        self.created_at = attributes[:'created_at']
      end
      
      if attributes[:'created_by']
        self.created_by = attributes[:'created_by']
      end
      
      if attributes[:'dependencies']
        if (value = attributes[:'dependencies']).is_a?(Array)
          self.dependencies = value
        end
      end
      
      if attributes[:'environment']
        if (value = attributes[:'environment']).is_a?(Array)
          self.environment = value
        end
      end
      
      if attributes[:'error_message']
        self.error_message = attributes[:'error_message']
      end
      
      if attributes[:'fqn']
        self.fqn = attributes[:'fqn']
      end
      
      if attributes[:'name']
        self.name = attributes[:'name']
      end
      
      if attributes[:'provides']
        if (value = attributes[:'provides']).is_a?(Array)
          self.provides = value
        end
      end
      
      if attributes[:'resource']
        self.resource = attributes[:'resource']
      end
      
      if attributes[:'resources']
        if (value = attributes[:'resources']).is_a?(Array)
          self.resources = value
        end
      end
      
      if attributes[:'staging_pipeline']
        self.staging_pipeline = attributes[:'staging_pipeline']
      end
      
      if attributes[:'staging_pipeline_fqn']
        self.staging_pipeline_fqn = attributes[:'staging_pipeline_fqn']
      end
      
      if attributes[:'state']
        self.state = attributes[:'state']
      end
      
      if attributes[:'tags']
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end
      
      if attributes[:'updated_at']
        self.updated_at = attributes[:'updated_at']
      end
      
      if attributes[:'updated_by']
        self.updated_by = attributes[:'updated_by']
      end
      
      if attributes[:'uuid']
        self.uuid = attributes[:'uuid']
      end
      
      if attributes[:'version_id']
        self.version_id = attributes[:'version_id']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          dependencies == o.dependencies &&
          environment == o.environment &&
          error_message == o.error_message &&
          fqn == o.fqn &&
          name == o.name &&
          provides == o.provides &&
          resource == o.resource &&
          resources == o.resources &&
          staging_pipeline == o.staging_pipeline &&
          staging_pipeline_fqn == o.staging_pipeline_fqn &&
          state == o.state &&
          tags == o.tags &&
          updated_at == o.updated_at &&
          updated_by == o.updated_by &&
          uuid == o.uuid &&
          version_id == o.version_id
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [created_at, created_by, dependencies, environment, error_message, fqn, name, provides, resource, resources, staging_pipeline, staging_pipeline_fqn, state, tags, updated_at, updated_by, uuid, version_id].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
