=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class RolloutConfig
    # The number of seconds a job should be cycling between flapping states before being considered in an errored state and stop attempting any restarts.
    attr_accessor :errored_state_window

    # The minimum number of tasks that must have failed in order to trigger a flapping state.
    attr_accessor :flapping_minimum_restarts

    # The number of instances that must have restarted in a given window for flapping to kick in.
    attr_accessor :flapping_percent

    # The number of seconds over which the job's flapping window operates.
    attr_accessor :flapping_window

    # If this field is non-zero then it will be used to represent how long an old version of a job is allowed to exist in the cluster. If this is zero then no fixed length is established and updates will be applied by starting a new version and then only when that instance is running will the old instance be killed.
    attr_accessor :force_stop_old_instances_after

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'errored_state_window' => :'errored_state_window',
        
        :'flapping_minimum_restarts' => :'flapping_minimum_restarts',
        
        :'flapping_percent' => :'flapping_percent',
        
        :'flapping_window' => :'flapping_window',
        
        :'force_stop_old_instances_after' => :'force_stop_old_instances_after'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'errored_state_window' => :'Integer',
        :'flapping_minimum_restarts' => :'Integer',
        :'flapping_percent' => :'Float',
        :'flapping_window' => :'Integer',
        :'force_stop_old_instances_after' => :'Integer'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'errored_state_window']
        self.errored_state_window = attributes[:'errored_state_window']
      end
      
      if attributes[:'flapping_minimum_restarts']
        self.flapping_minimum_restarts = attributes[:'flapping_minimum_restarts']
      end
      
      if attributes[:'flapping_percent']
        self.flapping_percent = attributes[:'flapping_percent']
      end
      
      if attributes[:'flapping_window']
        self.flapping_window = attributes[:'flapping_window']
      end
      
      if attributes[:'force_stop_old_instances_after']
        self.force_stop_old_instances_after = attributes[:'force_stop_old_instances_after']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          errored_state_window == o.errored_state_window &&
          flapping_minimum_restarts == o.flapping_minimum_restarts &&
          flapping_percent == o.flapping_percent &&
          flapping_window == o.flapping_window &&
          force_stop_old_instances_after == o.force_stop_old_instances_after
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [errored_state_window, flapping_minimum_restarts, flapping_percent, flapping_window, force_stop_old_instances_after].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
