=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SwaggerClient
  class VirtualNetwork
    # Network's fully-qualified name.
    attr_accessor :fqn

    # Network's local name.
    attr_accessor :name

    # Network description.
    attr_accessor :description

    # Network's unique ID.
    attr_accessor :uuid

    # Contains information about the network's subnet.
    attr_accessor :subnet_info

    # UNIX timestamp when the network was last updated.
    attr_accessor :updated_at

    # Principal name of user who last updated the network.
    attr_accessor :updated_by

    # UNIX timestamp when the network was created.
    attr_accessor :created_at

    # Principal name of user who created the network.
    attr_accessor :created_by

    # A list of network endpoints in the network.
    attr_accessor :network_end_points

    # Auto-incrementing version number for the network.
    attr_accessor :version_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'fqn' => :'fqn',
        
        :'name' => :'name',
        
        :'description' => :'description',
        
        :'uuid' => :'uuid',
        
        :'subnet_info' => :'subnet_info',
        
        :'updated_at' => :'updated_at',
        
        :'updated_by' => :'updated_by',
        
        :'created_at' => :'created_at',
        
        :'created_by' => :'created_by',
        
        :'network_end_points' => :'network_end_points',
        
        :'version_id' => :'version_id'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'fqn' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'uuid' => :'String',
        :'subnet_info' => :'SubnetInfo',
        :'updated_at' => :'Float',
        :'updated_by' => :'String',
        :'created_at' => :'Float',
        :'created_by' => :'String',
        :'network_end_points' => :'Array<VirtualNetworkEndpoint>',
        :'version_id' => :'Integer'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'fqn']
        self.fqn = attributes[:'fqn']
      end
      
      if attributes[:'name']
        self.name = attributes[:'name']
      end
      
      if attributes[:'description']
        self.description = attributes[:'description']
      end
      
      if attributes[:'uuid']
        self.uuid = attributes[:'uuid']
      end
      
      if attributes[:'subnet_info']
        self.subnet_info = attributes[:'subnet_info']
      end
      
      if attributes[:'updated_at']
        self.updated_at = attributes[:'updated_at']
      end
      
      if attributes[:'updated_by']
        self.updated_by = attributes[:'updated_by']
      end
      
      if attributes[:'created_at']
        self.created_at = attributes[:'created_at']
      end
      
      if attributes[:'created_by']
        self.created_by = attributes[:'created_by']
      end
      
      if attributes[:'network_end_points']
        if (value = attributes[:'network_end_points']).is_a?(Array)
          self.network_end_points = value
        end
      end
      
      if attributes[:'version_id']
        self.version_id = attributes[:'version_id']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fqn == o.fqn &&
          name == o.name &&
          description == o.description &&
          uuid == o.uuid &&
          subnet_info == o.subnet_info &&
          updated_at == o.updated_at &&
          updated_by == o.updated_by &&
          created_at == o.created_at &&
          created_by == o.created_by &&
          network_end_points == o.network_end_points &&
          version_id == o.version_id
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [fqn, name, description, uuid, subnet_info, updated_at, updated_by, created_at, created_by, network_end_points, version_id].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SwaggerClient.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
