=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::CreateDockerJobResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CreateDockerJobResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::CreateDockerJobResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreateDockerJobResponse' do
    it 'should create an instact of CreateDockerJobResponse' do
      @instance.should be_a(SwaggerClient::CreateDockerJobResponse) 
    end
  end
  describe 'test attribute "location"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

