=begin
Apcera APIs

REST APIs used to manage an Apcera cluster and its resources. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Namespace
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Namespace' do
  before do
    # run before each test
    @instance = SwaggerClient::Namespace.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Namespace' do
    it 'should create an instact of Namespace' do
      @instance.should be_a(SwaggerClient::Namespace) 
    end
  end
  describe 'test attribute "namespace"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

